name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pyyaml
  - mlflow==2.8.1
  - hydra-core=1.3.2
  - pip=23.3.1
  - pip:
      - wandb==0.17.5
      - hydra-joblib-launcher==1.2.0
      - databricks-cli==0.18.0

