name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.4
  - python=3.10.14
  - pandas=2.1.3
  - scipy=1.14.0
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.17.5
      - databricks-cli==0.18.0
